language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm
before_script:
  - composer self-update
  - composer install --dev
  - phpenv rehash
script: phpunit -v --colors --coverage-text
notifications:
  email:
    - artodeto@bazzline.net
